name: Test AWS OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  verify-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::518761466634:role/GitHubActionsOIDCRole
          aws-region: us-east-1
          audience: sts.amazonaws.com
          output-env-credentials: true

      - name: Verify assumed role
        run: aws sts get-caller-identity
